"""
PreToolUse guard: refuse agent edits to committed MEASUREMENTS.

WHY THIS EXISTS
    471 CSVs under `data/` are this project's contribution. They are measurements, written once
    by a sweep or a logger, and nothing should ever hand-edit one.

    The failure this closes is silent. `analysis/audit_claims.py` renders its expected string
    FROM the CSVs at audit time, so a corrupted number does not fail the audit - it becomes the
    number the audit demands the paper contain. The run would report "284 of 284 claims verified"
    against altered data. CLAUDE.md already records that this codebase's defects "do not look
    like defects"; this is the one that would be invisible to every check the repo has.

WHAT IS PROTECTED, AND WHAT IS DELIBERATELY NOT
    Blocked: EVERYTHING except `.md` under the five measurement directories, plus
    `data/MANIFEST.json`, which is GENERATED by build_data_manifest.py and must never be
    hand-reconciled into agreement. Default-deny, because a list of protected extensions has to
    be remembered every time a tool learns to write a new one - see the comment on
    EDITABLE_SUFFIXES_INSIDE_DATA for the mutation run that forced this.

    ✅ Allowed: every `.md`. That exception is not a loophole, it is most of the work - CLAUDE.md
    requires every data directory to carry a README, and the session run sheets
    (`SESSION-D-RUNSHEET.md`, `SESSION-E-RUNSHEET.md`) live INSIDE data/frequency-sweeps/ and are
    edited constantly. A guard that blocked those would be removed within a day, which is worse
    than no guard.

FAIL-OPEN, ON PURPOSE
    Malformed or absent stdin exits 0 with a warning rather than blocking. This guard protects
    against an accident, not an adversary, and a hook that bricks all editing when it breaks
    would be turned off - at which point it protects nothing. The warning goes to stderr so the
    failure is visible rather than silent.

    ⛔ Do NOT "harden" this into fail-closed without also making the hook impossible to break.

Run: python tools/claude-hooks/guard_measurement_files.py   (reads hook JSON on stdin)
"""

import json
import sys

# Directories holding data that was MEASURED rather than written. Kept as an explicit list
# rather than "everything under data/" because data/ also holds READMEs, run sheets and the
# licence files, all of which are ordinary prose.
PROTECTED_DIRECTORIES = (
    "data/frequency-sweeps",
    "data/stability-runs",
    "data/probes",
    "data/afterburner-profiles",
    "data/hwinfo-data",
)

# Generated files outside those directories that must be REBUILT rather than edited.
PROTECTED_EXACT = ("data/manifest.json",)

# ⛔ Inside a measurement directory the rule is DEFAULT-DENY, and prose is the only exception.
#
# The first version of this file listed the protected extensions instead - `.csv`, `.json`,
# `.cfg` - with a separate "always editable" list beside it. A mutation run found that list was
# DEAD CODE: a README could not reach it, because a `.md` file already failed the positive
# suffix test one line earlier. The guard's most important allowance was therefore untested and
# unreachable, and the suite passed with it deleted.
#
# 🔑 Default-deny also fixes the real hazard the positive list carried: the stability logger
# writes `_logger-stdout.txt` and `_logger-stderr.txt` into data/stability-runs/, and those are
# run records. A list of protected extensions has to be remembered every time a tool learns to
# write a new one. This does not.
EDITABLE_SUFFIXES_INSIDE_DATA = (".md",)


def normalise(filePath):
    """A repo-relative, forward-slashed, lowercased path for comparison.

    Windows is case-insensitive and hands back backslashes, and the hook receives an absolute
    path. Comparison happens on a normalised form so that `C:\\...\\Data\\Frequency-Sweeps\\x.csv`
    and `data/frequency-sweeps/x.csv` reach the same verdict.
    """
    return str(filePath).replace("\\", "/").lower()


def verdict(filePath):
    """None if the edit is allowed, otherwise the sentence explaining the refusal."""
    if not filePath:
        return None
    path = normalise(filePath)

    for exact in PROTECTED_EXACT:
        if path.endswith(exact):
            return (f"{filePath} is GENERATED by analysis/build_data_manifest.py. "
                    "Re-run that instead of editing it - a hand-reconciled manifest agrees with "
                    "the paper without being true of the data.")

    for directory in PROTECTED_DIRECTORIES:
        if f"/{directory}/" in path or path.startswith(f"{directory}/"):
            if any(path.endswith(suffix) for suffix in EDITABLE_SUFFIXES_INSIDE_DATA):
                return None
            return (f"{filePath} is a committed MEASUREMENT and must not be edited. "
                    "The claims auditor renders its expected strings from these files, so an "
                    "edit here would be verified rather than caught. If the value is wrong, "
                    "re-measure it or record the correction in the directory's README.")
    return None


def editedPath(payload):
    """The file a tool call would write, or None if this call does not write one."""
    toolInput = payload.get("tool_input") or {}
    return toolInput.get("file_path") or toolInput.get("notebook_path")


def main():
    try:
        payload = json.load(sys.stdin)
    except (json.JSONDecodeError, ValueError, UnicodeDecodeError) as error:
        print(f"[guard] could not read hook input, allowing the edit: {error}", file=sys.stderr)
        return 0

    reason = verdict(editedPath(payload))
    if reason is None:
        return 0

    print(f"[guard] BLOCKED. {reason}", file=sys.stderr)
    return 2


if __name__ == "__main__":
    sys.exit(main())
